version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: partnerup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      TZ: Europe/Madrid
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d partnerup"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      - TZ=Europe/Madrid
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - TZ=Europe/Madrid
    depends_on:
      adminer:
        condition: service_started

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/partnerup
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
      TZ: Europe/Madrid
    ports:
      - "8080:8080"
    depends_on:
      frontend:
        condition: service_started

volumes:
  postgres_data:
