spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/partnerup
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080