spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/partnerup
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

riot:
  api:
    key: RGAPI-b143a478-69b3-4a1f-890a-4ea696984167
  profile:
    icon:
      base:
        url: https://ddragon.leagueoflegends.com/cdn/14.9.1/img/profileicon/