spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/partnerup
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

riot:
  api:
    key: RGAPI-5c8baad3-d114-4286-bf7f-a262a828bf06
  profile:
    icon:
      base:
        url: https://ddragon.leagueoflegends.com/cdn/14.9.1/img/profileicon/