spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/partnerup
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

riot:
  api:
    key: RGAPI-d4a65952-399f-4de9-b0df-433e90d652b1
  profile:
    icon:
      base:
        url: https://ddragon.leagueoflegends.com/cdn/14.9.1/img/profileicon/

discord:
  bot:
    token: MTI0MDM2ODAzMzk5NDY0MTQ3MQ.GgD_Yz.y3B8Ql976ozetlt7pNbT92bvCgHUQHGVqVdDJw
  guild:
    id: 1242122335931076608