spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/partnerup
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

riot:
  api:
    key: RGAPI-fd43762a-ee05-42c4-9de9-75e0cb9eab0d
  profile:
    icon:
      base:
        url: https://ddragon.leagueoflegends.com/cdn/14.9.1/img/profileicon/

discord:
  bot:
    token: MTI0MDM2ODAzMzk5NDY0MTQ3MQ.GRLFSF.fMpT1e-I5PlRKQnhmfs3TkwE1WMjm3m-MbmGiQ
  guild:
    id: 1242122335931076608
